#!/bin/bash
HOMEAGENT=/opt/home-agent
VIRTUAL_ENV=${HOMEAGENT}/env
PYTHON_HOME=${VIRTUAL_ENV}
PATH=${VIRTUAL_ENV}/bin:${PATH}

DISPLAY=:0
XDG_SESSION_DESKTOP=cinnamon
XDG_SESSION_TYPE=x11
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
